### ISSUE TITLE
建议为词库文件标明和更正时间，方便辩识不同版本

### ISSUE THREAD

**Issue by kitty-panics** [yanhuacuo/98wubi-weasel#1]
以 **wubi98_U.dict.yaml** 词库文件为例，在 [永硕网盘]、[yanhuacuo/98wubi-unicode] 和 [yanhuacuo/98wubi-weasel] 这三个地方分别下载这个词库文件。

它们第三行的日期都为 `# 20190730`，但词库的内容又不相同。

[永硕网盘]: http://ys-d.ysepan.com/602672929/916104814/SJ6VfTp544I7H3O56MJ40b/wubi98_U.dict.yaml
[yanhuacuo/98wubi-unicode]: https://github.com/yanhuacuo/98wubi-unicode/blob/master/wubi98_U.dict.yaml
[yanhuacuo/98wubi-weasel]: https://github.com/yanhuacuo/98wubi-weasel/blob/master/patch/data/wubi98_U.dict.yaml

**Comment by yanhuacuo** [comment]
暂时以永硕网盘为准，github 上的资源缺乏系统整理。资源库在筹备字集扩编与扩H区支持计划，实在有点忙。
